<#-- @ftlvariable name="isDockerEnabled" type="java.lang.Boolean" -->
# General
This application has been generated by WebApplicationGenerator.

<#if isDockerEnabled>
## Docker
You have chosen Docker as your deployment option. Therefore, among others two files have been generated:
- buildAndRun.sh: You can run this file to build your application, build a Docker image from it and finally run it locally on your machine.
- Dockerfile: The building plan of your Docker image.
</#if>
