<#-- @ftlvariable name="isDeploymentEnabled" type="java.lang.Boolean" -->
<#-- @ftlvariable name="isSecurityEnabled" type="java.lang.Boolean" -->
# General
This application has been generated by WebApplicationGenerator.

<#if isDeploymentEnabled>
## Docker
You have chosen Docker as your deployment option. Therefore, among others two files have been generated:
- buildAndRun.sh: You can run this file to build your application, build a Docker image from it and finally run it locally on your machine.
- Dockerfile: The building plan of your Docker image.
Due to zipping and unzipping the Sourcecode currently all files are not executable. Hence, to run buildAndRun.sh the permission has to be set properly, e.g. with chmod 770.
</#if>

<#if isSecurityEnabled>
## Security
In your application a default security configuration has been setup. The default-username and default-password you have set in your request were automatically configured. If you left that data empty, default values have been used. You can check the Security-Class in request-model for the used values.
Please disable the seeded default-username & -password in a Production environment and properly set your login-information!
Also mind that h2-console is active per default and excluded to authentication (if you have h2-console enabled). You should disable that in your Production environment.
Default username and password can be found in application.properties.
</#if>
