<#-- @ftlvariable name="isDockerEnabled" type="java.lang.Boolean" -->
# General
This application has been generated by WebApplicationGenerator.

<#if isDockerEnabled>
## Docker
You have chosen Docker as your deployment option. Therefore, among others two files have been generated:
- buildAndRun.sh: You can run this file to build your application, build a Docker image from it and finally run it locally on your machine.
- Dockerfile: The building plan of your Docker image.
Due to zipping and unzipping the Sourcecode currently all files are not executable. Hence, to run buildAndRun.sh the permission has to be set properly, e.g. with chmod 770.
</#if>
